# Generated by Django 5.1.4 on 2026-01-09 04:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False, help_text='System categories cannot be deleted')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['category_type', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('credit_card', 'Credit Card'), ('savings', 'Savings')], max_length=20)),
                ('institution', models.CharField(help_text='e.g., American Express', max_length=100)),
                ('last_four', models.CharField(blank=True, default='', help_text='Last 4 digits', max_length=4)),
                ('is_personal', models.BooleanField(default=False, help_text='True for personal cards used for business expenses')),
                ('is_active', models.BooleanField(default=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Starting balance when account was added', max_digits=12)),
                ('opening_balance_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.UUIDField()),
                ('object_repr', models.CharField(max_length=500)),
                ('changes', models.JSONField(default=dict, help_text='Before/after values')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CSVImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='csv_imports/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('errors', models.JSONField(default=list, help_text='List of row errors')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='csv_imports', to='finance.account')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSV Import',
                'verbose_name_plural': 'CSV Imports',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=500)),
                ('vendor', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20)),
                ('day_of_month', models.IntegerField(help_text='Day of month to generate (1-31)')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for ongoing', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_transactions', to='finance.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_transactions', to='finance.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due'],
            },
        ),
        migrations.CreateModel(
            name='TaxAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quarter', models.IntegerField(help_text='1-4')),
                ('year', models.IntegerField()),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12)),
                ('actual_net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('alert_triggered', models.BooleanField(default=False)),
                ('alert_date', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-quarter'],
                'unique_together': {('quarter', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer'), ('owners_draw', "Owner's Draw")], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('vendor', models.CharField(blank=True, default='', max_length=200)),
                ('reference_number', models.CharField(blank=True, default='', help_text='Check number, confirmation code, etc.', max_length=100)),
                ('is_recurring', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.account')),
                ('category', models.ForeignKey(blank=True, help_text='Required for income/expense, null for transfers', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('recurring_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='finance.recurringtransaction')),
                ('transfer_to_account', models.ForeignKey(blank=True, help_text='For transfers only: destination account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='finance.account')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='receipts/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('jpg', 'JPEG'), ('png', 'PNG')], max_length=10)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('ocr_processed', models.BooleanField(default=False)),
                ('ocr_vendor', models.CharField(blank=True, default='', max_length=200)),
                ('ocr_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ocr_date', models.DateField(blank=True, null=True)),
                ('ocr_raw_text', models.TextField(blank=True, default='')),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='OCR confidence score 0.00-1.00', max_digits=3, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipts', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='finance.transaction')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
