# Generated by Django 5.1.4 on 2026-01-09 04:40

from django.db import migrations


def seed_categories(apps, schema_editor):
    """Seed default expense and income categories."""
    Category = apps.get_model('finance', 'Category')

    # Expense categories
    expense_categories = [
        ('Software & Subscriptions', 'Monthly software and SaaS subscriptions', 1),
        ('Equipment', 'Computer hardware, office equipment', 2),
        ('Professional Services', 'Legal, accounting, consulting fees', 3),
        ('Advertising & Marketing', 'Ads, marketing materials, promotions', 4),
        ('Office Supplies', 'Paper, pens, general office supplies', 5),
        ('Education & Training', 'Courses, books, conferences', 6),
        ('Travel', 'Business travel expenses', 7),
        ('Meals & Entertainment', 'Business meals, client entertainment', 8),
        ('Bank Fees & Interest', 'Account fees, interest charges', 9),
        ('Miscellaneous', 'Other business expenses', 10),
    ]

    for name, description, order in expense_categories:
        Category.objects.create(
            name=name,
            category_type='expense',
            description=description,
            is_system=True,
            is_active=True,
            display_order=order
        )

    # Income categories
    income_categories = [
        ('Service Revenue', 'Income from services provided', 1),
        ('Product Revenue', 'Income from product sales', 2),
        ('Refunds', 'Refunds received', 3),
        ('Owner Contributions', 'Capital contributed by owner', 4),
        ('Other Income', 'Miscellaneous income', 5),
    ]

    for name, description, order in income_categories:
        Category.objects.create(
            name=name,
            category_type='income',
            description=description,
            is_system=True,
            is_active=True,
            display_order=order
        )

    print(f'Created {len(expense_categories)} expense categories.')
    print(f'Created {len(income_categories)} income categories.')


def reverse_categories(apps, schema_editor):
    """Remove seeded categories."""
    Category = apps.get_model('finance', 'Category')
    Category.objects.filter(is_system=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_categories),
    ]
