# Generated by Django 5.1.4 on 2026-01-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_add_auditlog_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'category_type'), name='unique_category_name_per_type'),
        ),
    ]
