# Generated by Django 5.1.4 on 2026-08-08 04:25

import aegis.core.fields
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=aegis.core.fields.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=aegis.core.fields.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=aegis.core.fields.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('tenant_code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=16)),
            ],
            options={
                'ordering': ['tenant_code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=aegis.core.fields.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('is_system', models.BooleanField(default=False)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='aegis_core.permission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='aegis_core.tenant')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=aegis.core.fields.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('platform_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='aegis_core.platformuser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='aegis_core.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='aegis_core.tenant')),
            ],
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=aegis.core.fields.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('object_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=500)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='aegis_core.platformuser')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='aegis_core.tenant')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderIdentity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=aegis.core.fields.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=255)),
                ('platform_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='aegis_core.platformuser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject'), name='uq_provideridentity_provider_subject')],
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_role_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('tenant', 'platform_user', 'role'), name='uq_membership_tenant_user_role'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['tenant', '-occurred_at'], name='auditevent_tenant_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', '-occurred_at'], name='auditevent_action_time_idx'),
        ),
    ]
