# Generated by Django 5.1.4 on 2026-08-08 12:43

import aegis.core.fields
import aegis.core_hr.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aegis_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=aegis.core.fields.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='aegis_core.tenant')),
            ],
            options={
                'ordering': ['company_code'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            bases=(aegis.core_hr.models.TenantConsistencyMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=aegis.core.fields.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('department_code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='aegis_core_hr.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='aegis_core.tenant')),
            ],
            options={
                'ordering': ['department_code'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            bases=(aegis.core_hr.models.TenantConsistencyMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=aegis.core.fields.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('type_code', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=255)),
                ('classification', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('CONTINGENT', 'Contingent')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='aegis_core.tenant')),
            ],
            options={
                'ordering': ['type_code'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            bases=(aegis.core_hr.models.TenantConsistencyMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=aegis.core.fields.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('status_code', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=255)),
                ('system_category', models.CharField(choices=[('ACTIVE', 'Active'), ('LEAVE', 'Leave'), ('TERMINATED', 'Terminated')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='aegis_core.tenant')),
            ],
            options={
                'verbose_name_plural': 'employment statuses',
                'ordering': ['status_code'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            bases=(aegis.core_hr.models.TenantConsistencyMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=aegis.core.fields.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('job_code', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='aegis_core.tenant')),
            ],
            options={
                'ordering': ['job_code'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            bases=(aegis.core_hr.models.TenantConsistencyMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=aegis.core.fields.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('location_code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('region_state', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='aegis_core.tenant')),
            ],
            options={
                'ordering': ['location_code'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            bases=(aegis.core_hr.models.TenantConsistencyMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=aegis.core.fields.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('preferred_name', models.CharField(blank=True, max_length=128)),
                ('hire_date', models.DateField()),
                ('original_hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='aegis_core_hr.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='aegis_core_hr.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='aegis_core_hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='aegis_core.tenant')),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='aegis_core_hr.employeetype')),
                ('employment_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='aegis_core_hr.employmentstatus')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='aegis_core_hr.job')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='aegis_core_hr.location')),
            ],
            options={
                'ordering': ['employee_number'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            bases=(aegis.core_hr.models.TenantConsistencyMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('tenant', 'company_code'), name='uq_company_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('tenant', 'department_code'), name='uq_department_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('parent_department', models.F('id')), _negated=True), name='ck_department_parent_not_self'),
        ),
        migrations.AddConstraint(
            model_name='employeetype',
            constraint=models.UniqueConstraint(fields=('tenant', 'type_code'), name='uq_emptype_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='employmentstatus',
            constraint=models.UniqueConstraint(fields=('tenant', 'status_code'), name='uq_empstatus_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('tenant', 'job_code'), name='uq_job_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('tenant', 'location_code'), name='uq_location_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'hire_date'], name='emp_tenant_hire_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'termination_date'], name='emp_tenant_term_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee_number'), name='uq_employee_tenant_number'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('manager', models.F('id')), _negated=True), name='ck_employee_manager_not_self'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('termination_date__isnull', True), ('termination_date__gte', models.F('hire_date')), _connector='OR'), name='ck_employee_term_after_hire'),
        ),
    ]
