# Generated by Django 5.2.9 on 2025-12-29 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodebaseMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("captured_at", models.DateTimeField()),
                ("total_tests", models.IntegerField()),
                ("tests_passing", models.IntegerField(null=True)),
                ("total_python_files", models.IntegerField()),
                ("total_lines_of_code", models.IntegerField(null=True)),
                ("total_models", models.IntegerField()),
                ("total_endpoints", models.IntegerField()),
                ("total_apps", models.IntegerField()),
                ("third_party_services", models.IntegerField()),
                ("metrics_json", models.JSONField(default=dict)),
                ("imported_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Codebase Metric",
                "verbose_name_plural": "Codebase Metrics",
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("executive_summary", "Executive Summary"),
                            ("pitch_deck", "Pitch Deck"),
                            ("financial_model", "Financial Model"),
                            ("cost_analysis", "Cost Analysis"),
                            ("strategic_plan", "Strategic Plan"),
                            ("tech_architecture", "Technical Architecture"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="wlj/documents/")),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("download_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["document_type", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("provider", models.CharField(max_length=100)),
                ("product", models.CharField(max_length=100)),
                ("purpose", models.CharField(max_length=200)),
                (
                    "cost_1k_low",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cost_1k_high",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cost_10k_low",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cost_10k_high",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cost_50k_low",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cost_50k_high",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("current_plan", models.CharField(blank=True, max_length=100)),
                ("recommended_plan", models.CharField(blank=True, max_length=100)),
                ("key_limit", models.CharField(blank=True, max_length=200)),
                ("upgrade_trigger", models.CharField(blank=True, max_length=200)),
                ("source_url", models.URLField(blank=True)),
                ("date_checked", models.DateField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service Cost",
                "verbose_name_plural": "Service Costs",
                "ordering": ["category", "provider"],
            },
        ),
        migrations.CreateModel(
            name="DocumentDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wlj.document"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-downloaded_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        choices=[
                            ("conservative", "Conservative"),
                            ("base_case", "Base Case"),
                            ("aggressive", "Aggressive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField()),
                ("paying_users", models.IntegerField()),
                (
                    "user_growth_percent",
                    models.DecimalField(decimal_places=1, max_digits=5, null=True),
                ),
                ("arpu", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "annual_revenue",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("annual_costs", models.DecimalField(decimal_places=2, max_digits=12)),
                ("net_profit", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cumulative_profit",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "team_size",
                    models.DecimalField(decimal_places=1, max_digits=4, null=True),
                ),
                ("imported_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Financial Projection",
                "verbose_name_plural": "Financial Projections",
                "ordering": ["scenario", "year"],
                "unique_together": {("scenario", "year")},
            },
        ),
    ]
