"""
Tests for the secure product download portal.

Focus: authorization. Users must only see and download products granted to
them; unauthorized and anonymous users must not.
"""
import shutil
import tempfile

from django.contrib.auth.models import Group, User
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase, override_settings
from django.urls import reverse

from .models import Product
from .views import PASSWORD_CHANGE_REQUIRED_GROUP

_TEST_MEDIA = tempfile.mkdtemp(prefix='beacon-portal-test-')


def tearDownModule():
    shutil.rmtree(_TEST_MEDIA, ignore_errors=True)


@override_settings(MEDIA_ROOT=_TEST_MEDIA)
class PortalAuthorizationTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        # Start from a clean slate (the bootstrap migration seeds an 'aims' product).
        Product.objects.all().delete()
        cls.danny = User.objects.create_user('danny', password='pw-danny-123')
        cls.parker = User.objects.create_user('parker', password='pw-parker-123')

        cls.aims = Product.objects.create(
            name='AIMS',
            current_version='1.0.4',
            current_build='28',
            download_file=SimpleUploadedFile('AIMSField.ipa', b'fake-ipa-bytes'),
        )
        cls.wlj = Product.objects.create(
            name='Whole Life Journey',
            current_version='2.0.0',
            download_file=SimpleUploadedFile('wlj.zip', b'fake-zip-bytes'),
        )

        # Danny can access both; Parker only AIMS.
        cls.aims.authorized_users.add(cls.danny, cls.parker)
        cls.wlj.authorized_users.add(cls.danny)

    # --- My Products ---------------------------------------------------------

    def test_my_products_shows_only_authorized(self):
        self.client.login(username='parker', password='pw-parker-123')
        resp = self.client.get(reverse('products:my_products'))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'AIMS')
        self.assertNotContains(resp, 'Whole Life Journey')

    def test_my_products_requires_login(self):
        resp = self.client.get(reverse('products:my_products'))
        self.assertEqual(resp.status_code, 302)
        self.assertIn(reverse('products:login'), resp.url)

    # --- Product detail ------------------------------------------------------

    def test_authorized_user_sees_detail(self):
        self.client.login(username='parker', password='pw-parker-123')
        resp = self.client.get(reverse('products:detail', args=['aims']))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Download Latest Version')

    def test_detail_shows_version_and_build(self):
        self.client.login(username='parker', password='pw-parker-123')
        resp = self.client.get(reverse('products:detail', args=['aims']))
        self.assertContains(resp, 'Current Version')
        self.assertContains(resp, '1.0.4')
        self.assertContains(resp, 'Current Build')
        self.assertContains(resp, '28')

    def test_unauthorized_user_detail_is_404(self):
        self.client.login(username='parker', password='pw-parker-123')
        resp = self.client.get(reverse('products:detail', args=[self.wlj.slug]))
        self.assertEqual(resp.status_code, 404)

    # --- Downloads -----------------------------------------------------------

    def test_authorized_download_succeeds(self):
        self.client.login(username='danny', password='pw-danny-123')
        resp = self.client.get(reverse('products:download', args=['aims']))
        self.assertEqual(resp.status_code, 200)
        self.assertIn('attachment', resp['Content-Disposition'])
        self.assertEqual(b''.join(resp.streaming_content), b'fake-ipa-bytes')

    def test_unauthorized_download_is_404(self):
        self.client.login(username='parker', password='pw-parker-123')
        resp = self.client.get(reverse('products:download', args=[self.wlj.slug]))
        self.assertEqual(resp.status_code, 404)

    def test_anonymous_download_redirects_to_login(self):
        resp = self.client.get(reverse('products:download', args=['aims']))
        self.assertEqual(resp.status_code, 302)
        self.assertIn(reverse('products:login'), resp.url)

    def test_disabled_download_is_404_even_for_authorized(self):
        self.aims.download_enabled = False
        self.aims.save()
        self.client.login(username='danny', password='pw-danny-123')
        resp = self.client.get(reverse('products:download', args=['aims']))
        self.assertEqual(resp.status_code, 404)


@override_settings(MEDIA_ROOT=_TEST_MEDIA)
class ProductModelTests(TestCase):
    def setUp(self):
        # The bootstrap migration seeds an 'aims' product; start clean.
        Product.objects.all().delete()

    def test_slug_autogenerated_from_name(self):
        p = Product.objects.create(name='Finance Tracker')
        self.assertEqual(p.slug, 'finance-tracker')

    def test_replacing_build_deletes_old_file(self):
        p = Product.objects.create(
            name='Brother Willies',
            download_file=SimpleUploadedFile('old.zip', b'old'),
        )
        old_storage = p.download_file.storage
        old_name = p.download_file.name
        self.assertTrue(old_storage.exists(old_name))

        p.download_file = SimpleUploadedFile('new.zip', b'new')
        p.save()

        self.assertFalse(old_storage.exists(old_name))
        self.assertTrue(p.download_file.storage.exists(p.download_file.name))

    def test_is_available_requires_file_and_enabled(self):
        p = Product.objects.create(name='No File')
        self.assertFalse(p.is_available)
        p.download_file = SimpleUploadedFile('x.exe', b'bytes')
        p.save()
        self.assertTrue(p.is_available)
        p.download_enabled = False
        self.assertFalse(p.is_available)

    def test_file_extension(self):
        p = Product.objects.create(
            name='Ext Test',
            download_file=SimpleUploadedFile('build.APK', b'bytes'),
        )
        self.assertEqual(p.file_extension, 'apk')


@override_settings(MEDIA_ROOT=_TEST_MEDIA)
class ForcedPasswordChangeTests(TestCase):
    def setUp(self):
        self.group, _ = Group.objects.get_or_create(name=PASSWORD_CHANGE_REQUIRED_GROUP)
        self.user = User.objects.create_user('newadmin', password='temp-pass-123')
        self.user.groups.add(self.group)

    def test_flagged_user_redirected_from_portal(self):
        self.client.login(username='newadmin', password='temp-pass-123')
        resp = self.client.get(reverse('products:my_products'))
        self.assertRedirects(resp, reverse('products:password_change'))

    def test_flagged_user_can_reach_change_page(self):
        self.client.login(username='newadmin', password='temp-pass-123')
        resp = self.client.get(reverse('products:password_change'))
        self.assertEqual(resp.status_code, 200)

    def test_changing_password_clears_flag_and_unblocks_portal(self):
        self.client.login(username='newadmin', password='temp-pass-123')
        resp = self.client.post(reverse('products:password_change'), {
            'old_password': 'temp-pass-123',
            'new_password1': 'Str0ng-New-Pass!42',
            'new_password2': 'Str0ng-New-Pass!42',
        })
        self.assertRedirects(resp, reverse('products:password_change_done'))
        self.user.refresh_from_db()
        self.assertFalse(self.user.groups.filter(name=PASSWORD_CHANGE_REQUIRED_GROUP).exists())
        # Portal is now accessible (session kept alive after password change).
        resp = self.client.get(reverse('products:my_products'))
        self.assertEqual(resp.status_code, 200)

    def test_unflagged_user_not_redirected(self):
        User.objects.create_user('plainuser', password='pw-plain-123')
        self.client.login(username='plainuser', password='pw-plain-123')
        resp = self.client.get(reverse('products:my_products'))
        self.assertEqual(resp.status_code, 200)


class BootstrapTests(TestCase):
    """The bootstrap migration seeds the admin + AIMS without any hardcoded
    password, and flags a freshly created admin to change it."""

    def test_admin_and_aims_seeded(self):
        self.assertTrue(User.objects.filter(username='dannyjenkins71@gmail.com').exists())
        self.assertTrue(Product.objects.filter(slug='aims').exists())

    def test_seeded_admin_flagged_for_password_change(self):
        admin = User.objects.get(username='dannyjenkins71@gmail.com')
        self.assertTrue(admin.groups.filter(name=PASSWORD_CHANGE_REQUIRED_GROUP).exists())

    def test_no_hardcoded_password_in_bootstrap_migration(self):
        import os
        import products.migrations as mig_pkg

        path = os.path.join(os.path.dirname(mig_pkg.__file__), '0002_bootstrap_portal.py')
        with open(path) as f:
            source = f.read()
        # No previously hardcoded password may appear anywhere in the migration.
        self.assertNotIn('Beacon!Temp2026', source)
        self.assertNotIn('Beacon2026', source)
