# Generated by Django 5.1.4 on 2026-07-27 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, help_text='Used in the product URL. Auto-generated from the name if left blank.', max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('current_version', models.CharField(blank=True, help_text="e.g. '1.4.0' or 'Build 42'. Shown to users on the product page.", max_length=60)),
                ('icon', models.ImageField(blank=True, help_text='Optional. Small square image shown next to the product.', null=True, upload_to='product_icons/')),
                ('download_file', models.FileField(blank=True, help_text='The latest build. Uploading a new file replaces the previous one.', null=True, upload_to='product_downloads/')),
                ('download_enabled', models.BooleanField(default=True, help_text='Uncheck to temporarily disable downloads without deleting the file.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_users', models.ManyToManyField(blank=True, help_text='Users allowed to see and download this product.', related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
