# Generated by Django 5.1.4 on 2026-07-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bootstrap_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_build',
            field=models.CharField(blank=True, help_text="e.g. '28'. Shown alongside the version on the product page.", max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_version',
            field=models.CharField(blank=True, help_text="e.g. '1.0.4'. Shown to users on the product page.", max_length=60),
        ),
    ]
