# Generated by Django 5.1.4 on 2026-07-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_current_build_alter_product_current_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bundle_id',
            field=models.CharField(blank=True, help_text='iOS bundle identifier (e.g. com.beaconinnovation.aims.field). Required for over-the-air install; set automatically from the IPA.', max_length=200),
        ),
    ]
